app = "bibliotech-online"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"  # Referencie seu Dockerfile

[env]
  PORT = "8000"
  MYSQL_HOST = "bibliotech.internal"
  MYSQL_PORT = "3306"
  MYSQL_DATABASE = "some_db"
  MYSQL_USER = "non_root_user"
  INIT_DB = 'true'
  DJANGO_SETTINGS_MODULE = "app.settings"

[http_service]
  internal_port = 8000
  force_https = true

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[deploy]
  release_command = "python manage.py migrate --noinput"